sudo: false
language: python
python:
  - "2.7"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x800x16"
before_script:
  - "export DISPLAY=:99.0"
addons:
  apt:
    packages:
      - libqt4-dev
      - pyside-tools
env:
  - USE_AVX_DEVELOP=false
  - USE_AVX_DEVELOP=true
install:
  - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
  - pip install pep8 coveralls
  - pip install --upgrade setuptools
  - if [ "$USE_AVX_DEVELOP" = true ]; then pip install pip install git+git://github.com/jamesremuscat/avx.git#develop; fi
script:
  - pep8 --ignore=E501 src
  - ./compileResources.sh
  - coverage run --source=staldates setup.py nosetests
after_success:
  coveralls
